USE [master]
GO

/****** Object:  Database [KaZaPy_DB]    Script Date: 04/22/2013 11:56:48 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'KaZaPy_DB')
DROP DATABASE [KaZaPy_DB]
GO

USE [master]
GO

/****** Object:  Database [KaZaPy_DB]    Script Date: 04/22/2013 11:56:48 ******/
CREATE DATABASE [KaZaPy_DB] ON  PRIMARY 
( NAME = N'KaZaPy_DB', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\KaZaPy_DB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'KaZaPy_DB_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\KaZaPy_DB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [KaZaPy_DB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KaZaPy_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [KaZaPy_DB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [KaZaPy_DB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [KaZaPy_DB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [KaZaPy_DB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [KaZaPy_DB] SET ARITHABORT OFF 
GO

ALTER DATABASE [KaZaPy_DB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [KaZaPy_DB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [KaZaPy_DB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [KaZaPy_DB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [KaZaPy_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [KaZaPy_DB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [KaZaPy_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [KaZaPy_DB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [KaZaPy_DB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [KaZaPy_DB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [KaZaPy_DB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [KaZaPy_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [KaZaPy_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [KaZaPy_DB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [KaZaPy_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [KaZaPy_DB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [KaZaPy_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [KaZaPy_DB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [KaZaPy_DB] SET  READ_WRITE 
GO

ALTER DATABASE [KaZaPy_DB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [KaZaPy_DB] SET  MULTI_USER 
GO

ALTER DATABASE [KaZaPy_DB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [KaZaPy_DB] SET DB_CHAINING OFF 
GO

