//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.Account
{


    public partial class OpenAuthProviders
    {

        /// <summary>
        /// providerDetails control.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour modifier, déplacez la déclaration de champ du fichier de concepteur dans le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView providerDetails;

    }
}
