//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18034
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestKaZaPy.ProcessingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageInfo", Namespace="http://schemas.datacontract.org/2004/07/WebService")]
    [System.SerializableAttribute()]
    public partial class ImageInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int AlbumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Album {
            get {
                return this.AlbumField;
            }
            set {
                if ((this.AlbumField.Equals(value) != true)) {
                    this.AlbumField = value;
                    this.RaisePropertyChanged("Album");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProcessingService.IProcessingService")]
    public interface IProcessingService {
        
        // CODEGEN : La génération du contrat de message depuis l'opération Upload n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessingService/Upload", ReplyAction="http://tempuri.org/IProcessingService/UploadResponse")]
        TestKaZaPy.ProcessingService.UploadResponse Upload(TestKaZaPy.ProcessingService.ImageUploadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessingService/Upload", ReplyAction="http://tempuri.org/IProcessingService/UploadResponse")]
        System.Threading.Tasks.Task<TestKaZaPy.ProcessingService.UploadResponse> UploadAsync(TestKaZaPy.ProcessingService.ImageUploadRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (ImageDownloadRequest) du message ImageDownloadRequest ne correspond pas à la valeur par défaut (Download)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessingService/Download", ReplyAction="http://tempuri.org/IProcessingService/DownloadResponse")]
        TestKaZaPy.ProcessingService.ImageDownloadResponse Download(TestKaZaPy.ProcessingService.ImageDownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessingService/Download", ReplyAction="http://tempuri.org/IProcessingService/DownloadResponse")]
        System.Threading.Tasks.Task<TestKaZaPy.ProcessingService.ImageDownloadResponse> DownloadAsync(TestKaZaPy.ProcessingService.ImageDownloadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImageUploadRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImageUploadRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TestKaZaPy.ProcessingService.ImageInfo ImageInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream ImageData;
        
        public ImageUploadRequest() {
        }
        
        public ImageUploadRequest(TestKaZaPy.ProcessingService.ImageInfo ImageInfo, System.IO.Stream ImageData) {
            this.ImageInfo = ImageInfo;
            this.ImageData = ImageData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadResponse {
        
        public UploadResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImageDownloadRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImageDownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TestKaZaPy.ProcessingService.ImageInfo ImageInfo;
        
        public ImageDownloadRequest() {
        }
        
        public ImageDownloadRequest(TestKaZaPy.ProcessingService.ImageInfo ImageInfo) {
            this.ImageInfo = ImageInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImageDownloadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImageDownloadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream ImageData;
        
        public ImageDownloadResponse() {
        }
        
        public ImageDownloadResponse(System.IO.Stream ImageData) {
            this.ImageData = ImageData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProcessingServiceChannel : TestKaZaPy.ProcessingService.IProcessingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessingServiceClient : System.ServiceModel.ClientBase<TestKaZaPy.ProcessingService.IProcessingService>, TestKaZaPy.ProcessingService.IProcessingService {
        
        public ProcessingServiceClient() {
        }
        
        public ProcessingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestKaZaPy.ProcessingService.UploadResponse TestKaZaPy.ProcessingService.IProcessingService.Upload(TestKaZaPy.ProcessingService.ImageUploadRequest request) {
            return base.Channel.Upload(request);
        }
        
        public void Upload(TestKaZaPy.ProcessingService.ImageInfo ImageInfo, System.IO.Stream ImageData) {
            TestKaZaPy.ProcessingService.ImageUploadRequest inValue = new TestKaZaPy.ProcessingService.ImageUploadRequest();
            inValue.ImageInfo = ImageInfo;
            inValue.ImageData = ImageData;
            TestKaZaPy.ProcessingService.UploadResponse retVal = ((TestKaZaPy.ProcessingService.IProcessingService)(this)).Upload(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestKaZaPy.ProcessingService.UploadResponse> TestKaZaPy.ProcessingService.IProcessingService.UploadAsync(TestKaZaPy.ProcessingService.ImageUploadRequest request) {
            return base.Channel.UploadAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestKaZaPy.ProcessingService.UploadResponse> UploadAsync(TestKaZaPy.ProcessingService.ImageInfo ImageInfo, System.IO.Stream ImageData) {
            TestKaZaPy.ProcessingService.ImageUploadRequest inValue = new TestKaZaPy.ProcessingService.ImageUploadRequest();
            inValue.ImageInfo = ImageInfo;
            inValue.ImageData = ImageData;
            return ((TestKaZaPy.ProcessingService.IProcessingService)(this)).UploadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestKaZaPy.ProcessingService.ImageDownloadResponse TestKaZaPy.ProcessingService.IProcessingService.Download(TestKaZaPy.ProcessingService.ImageDownloadRequest request) {
            return base.Channel.Download(request);
        }
        
        public System.IO.Stream Download(TestKaZaPy.ProcessingService.ImageInfo ImageInfo) {
            TestKaZaPy.ProcessingService.ImageDownloadRequest inValue = new TestKaZaPy.ProcessingService.ImageDownloadRequest();
            inValue.ImageInfo = ImageInfo;
            TestKaZaPy.ProcessingService.ImageDownloadResponse retVal = ((TestKaZaPy.ProcessingService.IProcessingService)(this)).Download(inValue);
            return retVal.ImageData;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestKaZaPy.ProcessingService.ImageDownloadResponse> TestKaZaPy.ProcessingService.IProcessingService.DownloadAsync(TestKaZaPy.ProcessingService.ImageDownloadRequest request) {
            return base.Channel.DownloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestKaZaPy.ProcessingService.ImageDownloadResponse> DownloadAsync(TestKaZaPy.ProcessingService.ImageInfo ImageInfo) {
            TestKaZaPy.ProcessingService.ImageDownloadRequest inValue = new TestKaZaPy.ProcessingService.ImageDownloadRequest();
            inValue.ImageInfo = ImageInfo;
            return ((TestKaZaPy.ProcessingService.IProcessingService)(this)).DownloadAsync(inValue);
        }
    }
}
